[package]
name = "mphf_experiments"
version = "0.1.0"
edition = "2021"

[lib]
name = "mphf_experiments"
crate-type = ["staticlib"]

[dependencies]
libc = "0.2"
mem_dbg = "0.2.4"
ph = "0.7.3"
ptr_hash = { path = "../../ptr_hash" }
rayon = "1.7.0"
